### ISSUE TITLE
How to use this script when I'm singning in by OSM.org account

### ISSUE THREAD

**Issue by jkonecny12** [gitouche-sur-osm/mapillary_takeout#1]
Hello,

How can I use this script when I sign-in by OSM.org account. Is there a way how to convert my account to a regular account?

Thank you and great work on creating this script!

**Comment by gitouche-sur-osm** [comment]
Hello,

I believe I was in the same situation a while ago. Try "Change Password" from your Mapillary profile page https://www.mapillary.com/dashboard/profile

This will set a new password in your Mapillary account only (not OSM).

**Comment by gitouche-sur-osm** [comment]
Did you get it to work with the password reset?

**Comment by jkonecny12** [comment]
It's telling me email has been sent but I never receive one... :(

**Comment by jkonecny12** [comment]
I don't really think they have my mail. I don't think they are reading it from the OSM.

**Comment by gitouche-sur-osm** [comment]
I suggest you get in touch with mapillary support. They are responsive and very helpful.

**Comment by jkonecny12** [comment]
Good point. Thanks! I'll reply here when and how it is solved.

**Comment by jkonecny12** [comment]
Hi again, it took me some time to solve everything but I finally have mapillary account now.

The problem seems to be that I had a typo in a mail address in the OSM.org account when I used it to create mapillary account. They used this mail but when I fixed it later on OSM.org it won't changed on the mapillary side. Mapillary support have helped me to change my mail address.
When solving the above I can use forgot my password feature to set password and everything works as it should.

Thanks for your help. Feel free to close this issue

**Comment by gitouche-sur-osm** [comment]
> Hi again, it took me some time to solve everything but I finally have mapillary account now.
> 
> The problem seems to be that I had a typo in a mail address in the OSM.org account when I used it to create mapillary account. They used this mail but when I fixed it later on OSM.org it won't changed on the mapillary side. Mapillary support have helped me to change my mail address.
> When solving the above I can use forgot my password feature to set password and everything works as it should.
> 
> Thanks for your help. Feel free to close this issue

Great :-) happy downloads!
