### ISSUE TITLE
Invalid characters for Windows filenames

### ISSUE THREAD

**Issue by developery-nl** [gitouche-sur-osm/mapillary_takeout#6]
Since filenames currently contain a colon ( : ) , windows users should adapt the output filename to prevent errors. Around line 155 a workable solution  would be for example

`sequence_name = (
    sequence["properties"]["captured_at"]
    + "_"
    + sequence["properties"]["created_at"]
)
sequence_name = sequence_name.replace(":", "_")`

**Comment by gitouche-sur-osm** [comment]
Nice find. I changed it in https://github.com/gitouche-sur-osm/mapillary_takeout/commit/33c6651187193f98d30083e55f53b5f8243b3a14 only for windows user as to not break compatibility for linux users.

I have no way to test on a Windows at the moment. Do you?

**Comment by chk1** [comment]
The fix works for me on Windows 10 

One caveat is that the path prefix seems to get filtered too, so paths like `E:\mapillary-archive` or `..\archive` give me "invalid path" errors, but that's another minor issue I think
