### ISSUE TITLE
Storing sequences by date only has some issues

### ISSUE THREAD

**Issue by chk1** [gitouche-sur-osm/mapillary_takeout#7]
I have (unfortunately) a lot of images tagged with the date 1970-01-01 (unixtime 0), from converting actioncam videos to image sequences and not fixing their dates. mapillary_takeout throws images from these sequences into one big folder.

I recognize this is my own fault for providing bad data, but it would be nice if the resulting folders had some kind of counter on it, or a sub-folder for each individual sequence (I hacked one in myself for my purposes).

I'm on Windows 10, Python 3.7 if that matters

**Comment by wosch** [comment]
The latest version has an option --subfolder to store the images by sequence
