### ISSUE TITLE
Feature request: add sequence to folder

### ISSUE THREAD

**Issue by mrAceT** [gitouche-sur-osm/mapillary_takeout#9]
Hi, 

You now save to the folder: YYYY-MM-DD

I am a programmer, but not very proficient in Python.. could you add the option to save to:

YYYY-MM-DD-[sequence-ID]

?

Or is that first set of numbers of a file name the sequence?

**Comment by wosch** [comment]
The latest version has an option --subfolder to store the images by sequence
